package com.smy.gutenberggui.view;

import com.gargoylesoftware.htmlunit.TextPage;
import java.io.IOException;


/**
 *
 * @author sam
 */
public class BookReadJframe extends javax.swing.JFrame {
    /**
     * Creates new form BookReadJframe
     */
    public BookReadJframe(String etext_no, MainFrame mainFrame) throws IOException {
        initComponents();
        
        // get scrollbar's current position
        this.jScrollPane2.getVerticalScrollBar().getModel().getValue();
        
        final TextPage page;
        page = mainFrame.getWebClient().getPage("https://www.gutenberg.org/cache/epub/" + etext_no+ "/pg" + etext_no + ".txt");
        this.bookTextArea.append(page.getContent());
        System.out.println(bookTextArea.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        geriButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Read a Book");
        setMaximumSize(new java.awt.Dimension(930, 630));
        setMinimumSize(new java.awt.Dimension(930, 630));
        setResizable(false);
        setSize(new java.awt.Dimension(930, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainJPanel.setMaximumSize(new java.awt.Dimension(930, 630));
        mainJPanel.setMinimumSize(new java.awt.Dimension(930, 630));
        mainJPanel.setPreferredSize(new java.awt.Dimension(930, 630));

        geriButton.setText("Geri");
        geriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButtonActionPerformed(evt);
            }
        });

        bookTextArea.setEditable(false);
        bookTextArea.setBackground(new java.awt.Color(255, 255, 255));
        bookTextArea.setColumns(20);
        bookTextArea.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        bookTextArea.setForeground(new java.awt.Color(0, 0, 0));
        bookTextArea.setLineWrap(true);
        bookTextArea.setRows(5);
        bookTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(bookTextArea);

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addContainerGap(750, Short.MAX_VALUE)
                .addComponent(geriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(geriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(mainJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriButtonActionPerformed
        
    }//GEN-LAST:event_geriButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bookTextArea;
    private javax.swing.JButton geriButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainJPanel;
    // End of variables declaration//GEN-END:variables
}
