package com.smy.gutenberggui.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.smy.gutenberggui.model.User;
import com.smy.gutenberggui.util.DbHelper;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sam
 */
public class LoginJframe extends javax.swing.JFrame {

    private DbHelper dbHelper;

    /**
     * Creates new form Login
     */
    public LoginJframe() {
        initComponents();
        this.dbHelper = new DbHelper();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailJlabel = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        passwordJLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        loginJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailJlabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        emailJlabel.setText("Email:");
        jPanel1.add(emailJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        emailJTextField.setBackground(new java.awt.Color(187, 187, 187));
        emailJTextField.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        emailJTextField.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.add(emailJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 388, -1));

        passwordJLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        passwordJLabel.setText("Password:");
        jPanel1.add(passwordJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(187, 187, 187));
        jPasswordField1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 390, -1));

        loginJButton.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 140, 60));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel1.setText("Gutenberg GUI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed

        Connection connection = null;
        try {
            String sql = "Select * from users Where LOWER(email)='" + this.emailJTextField.getText().toLowerCase()
                    + "' and LOWER(password)='" + new String(this.jPasswordField1.getPassword()).toLowerCase() + "'";
            connection = this.dbHelper.getConnection();
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(sql);

            if (resultSet.next()) {
                MainFrame mainFrame = new MainFrame(new User(this.emailJTextField.getText()), dbHelper);
                mainFrame.setLocationRelativeTo(null);
                mainFrame.setVisible(true);
                this.setVisible(false);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null,
                        "Email ve/veya şifre yanlış.",
                        "Hatalı Giriş",
                        JOptionPane.WARNING_MESSAGE);

                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginJframe.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(LoginJframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginJframe loginJframe = new LoginJframe();
                loginJframe.setVisible(true);
                loginJframe.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel emailJlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel passwordJLabel;
    // End of variables declaration//GEN-END:variables
}
