package com.smy.gutenberggui.view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.gargoylesoftware.htmlunit.WebClient;
import com.smy.gutenberggui.model.User;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class MainFrame extends javax.swing.JFrame {

    private BookSearchJpanel bookSearchJpanel;
    private BookResultsJpanel bookResultsJpanel;
    private CardLayout cardLayout;
    private WebClient webClient;
    private User user;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(User user) {
        this.webClient = new WebClient();
        this.user = user;
        webClient.getOptions().setThrowExceptionOnScriptError(false);

        initComponents();
        this.cardLayout = new CardLayout();
        this.bookResultsJpanel = new BookResultsJpanel(this);
        this.bookSearchJpanel = new BookSearchJpanel(this);
        this.mainPanel.setLayout(this.cardLayout);
        this.mainPanel.add(this.bookSearchJpanel, "bookSearchJpanel");
        this.mainPanel.add(this.bookResultsJpanel, "bookResultsJpanel");
        this.cardLayout.show(this.mainPanel, "bookSearchJpanel");

    }

    public User getUser() {
        return user;
    }

    public WebClient getWebClient() {
        return webClient;
    }

    public JPanel getMainPanel() {
        return this.mainPanel;
    }

    public CardLayout getCardLayout() {
        return this.cardLayout;
    }

    public BookSearchJpanel getBookSearchJpanel() {
        return bookSearchJpanel;
    }

    public BookResultsJpanel getBookResultsJpanel() {
        return bookResultsJpanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solJpanel = new javax.swing.JPanel();
        kitaplarimButton = new javax.swing.JButton();
        cikisYapButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gutenberg GUI");
        setSize(new java.awt.Dimension(930, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solJpanel.setBackground(new java.awt.Color(45, 47, 48));

        kitaplarimButton.setText("Kitaplarım");

        cikisYapButton.setText("Çıkış Yap");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setText("<html>\nGUTENBERG <br>\nGUI");

        javax.swing.GroupLayout solJpanelLayout = new javax.swing.GroupLayout(solJpanel);
        solJpanel.setLayout(solJpanelLayout);
        solJpanelLayout.setHorizontalGroup(
            solJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solJpanelLayout.createSequentialGroup()
                .addGroup(solJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(solJpanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(solJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kitaplarimButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(cikisYapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(solJpanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        solJpanelLayout.setVerticalGroup(
            solJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solJpanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(kitaplarimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cikisYapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        getContentPane().add(solJpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 630));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 650, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikisYapButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton kitaplarimButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel solJpanel;
    // End of variables declaration//GEN-END:variables
}
